//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Fractice.rc
//
#define IDR_MAINFRAME                   101
#define IDR_FB_CTX_BAR                  102
#define IDR_FB_CTX_ITEM                 103
#define IDR_FRACTICETYPE                104
#define IDR_GRADIENT                    105
#define IDR_HISTORY                     106
#define IDR_JOB_CONTROL                 107
#define IDR_JOB_CONTROL_CTX             108
#define IDR_LEVELS                      109
#define IDR_MODAL                       110
#define IDR_PALETTE                     111
#define IDR_RECORDING                   112
#define IDR_RECORD_CTX                  113
#define IDR_REPORT_HDR                  114
#define IDR_SERVER_CTX                  115
#define IDR_VIEW                        116
#define IDI_HIST_VIEW_POS               117
#define IDI_SORT_DOWN                   118
#define IDI_SORT_UP                     119
#define IDI_TC_LOOP_DOWN                120
#define IDI_TC_LOOP_UP                  121
#define IDI_TC_PAUSE_DOWN               122
#define IDI_TC_PAUSE_UP                 123
#define IDI_TC_PLAY_DOWN                124
#define IDI_TC_PLAY_UP                  125
#define IDI_TC_STOP_DOWN                126
#define IDI_TC_STOP_UP                  127
#define IDD_ABOUTBOX                    128
#define IDD_ADD_SERVER                  129
#define IDD_ADD_SERVER_LIST             130
#define IDD_ANTIALIAS                   131
#define IDD_BOUNDS                      132
#define IDD_COLOR_CYCLING               133
#define IDD_COLOR_MAPPING               134
#define IDD_COLOR_PICKER                135
#define IDD_COORDS                      136
#define IDD_FIND_SERVERS                137
#define IDD_GRADIENT                    138
#define IDD_IMAGE_SIZE                  139
#define IDD_IMAGE_SIZE_RES              140
#define IDD_JOB_CONTROL                 141
#define IDD_MIDI_SETUP                  142
#define IDD_MIDI_SETUP_ROW              143
#define IDD_MIX_MAIN                    144
#define IDD_MIX_MISC                    145
#define IDD_MIX_MOTION                  146
#define IDD_MSG_BOX                     147
#define IDD_MULTI_FILE                  148
#define IDD_OPTS_DISPLAY                149
#define IDD_OPTS_DOCUMENT               150
#define IDD_OPTS_ENGINE                 151
#define IDD_OPTS_GENERAL                152
#define IDD_OPTS_MIDI                   153
#define IDD_OPTS_NAVIGATE               154
#define IDD_OPTS_NETWORK                155
#define IDD_OPTS_PALETTE                156
#define IDD_ORIGIN_DRAG                 157
#define IDD_ORIGIN_LISSAJOUS            158
#define IDD_ORIGIN_PONG                 159
#define IDD_ORIGIN_RANDOM               160
#define IDD_PALETTE                     161
#define IDD_PALETTE_NAME                162
#define IDD_POSTER                      163
#define IDD_POSTER_PROGRESS             164
#define IDD_PROGRESS                    165
#define IDD_QUALITY                     166
#define IDD_RECORD                      167
#define IDD_RECORD_STATUS               168
#define IDD_RENDERING                   169
#define IDD_ROW_DIALOG_FORM             170
#define IDD_SELECT_IMAGES               171
#define IDD_SERVERS                     172
#define IDD_SERVERS_FOUND               173
#define IDD_SERVER_SHUTDOWN             174
#define IDD_SHUTDOWN_WARN               175
#define IDD_SLIDE_SHOW                  176
#define IDD_TRANSFORM                   177
#define IDS_ALL_PAL_FILTER              200
#define IDS_APP_ABOUT_TEXT              201
#define IDS_APP_HOME_PAGE_URL           202
#define IDS_APP_LICENSE                 203
#define IDS_APP_NO_SSE2                 204
#define IDS_AVI_FILTER                  205
#define IDS_BAD_COORDS                  206
#define IDS_BAD_DEMO_PROJECT            207
#define IDS_BAD_FORMAT                  208
#define IDS_BAD_ZOOM                    209
#define IDS_BMP_FILTER                  210
#define IDS_BT_APPEND                   211
#define IDS_BT_REPLACE                  212
#define IDS_CANT_ADD_TO_AVI             213
#define IDS_CANT_CREATE_BITMAP          214
#define IDS_CANT_CREATE_BMP_FOLDER      215
#define IDS_CANT_CREATE_DC              216
#define IDS_CANT_CREATE_DIRECTDRAW      217
#define IDS_CANT_CREATE_FRAME           218
#define IDS_CANT_CREATE_SURFACE         219
#define IDS_CANT_CREATE_THUMB           220
#define IDS_CANT_EXPORT_PALETTE         221
#define IDS_CANT_IMPORT_PALETTE         222
#define IDS_CANT_LAUNCH_BMP_THREAD      223
#define IDS_CANT_LAUNCH_ENGINE          224
#define IDS_CANT_READ_BITMAP            225
#define IDS_CANT_SET_DISPLAY_MODE       226
#define IDS_CANT_SET_EXCLUSIVE          227
#define IDS_CANT_WRITE_BITMAP           228
#define IDS_CBT_COLOR_CYCLING           229
#define IDS_CBT_COLOR_MAPPING           230
#define IDS_CBT_FILES                   231
#define IDS_CBT_HISTORY                 232
#define IDS_CBT_LEVELS                  233
#define IDS_CBT_MIXER                   234
#define IDS_CBT_PALETTE                 235
#define IDS_CBT_PARAMETERS              236
#define IDS_CBT_SLIDE_SHOW              237
#define IDS_DOCKABLE                    238
#define IDS_DOC_OPENING                 239
#define IDS_DOC_OPEN_FILTER             240
#define IDS_DOC_SAVE_FILTER             241
#define IDS_DOC_SAVING                  242
#define IDS_EDIT_REDO_FMT               243
#define IDS_EDIT_UNDO_FMT               244
#define IDS_EXCLUSIVE_WND_NAME          245
#define IDS_EXPORT                      246
#define IDS_FB_COL_MODIFIED             247
#define IDS_FB_COL_NAME                 248
#define IDS_FB_COL_SIZE                 249
#define IDS_FB_COL_TYPE                 250
#define IDS_FB_FILE_SUFFIX              251
#define IDS_FB_PALETTES                 252
#define IDS_FB_PROJECTS                 253
#define IDS_FILE_OVERWRITE_PROMPT       254
#define IDS_FSRV_BAD_IP_RANGE           255
#define IDS_FSRV_FINDING                256
#define IDS_FSRV_PROGRESS_CAP           257
#define IDS_FT_MANDELBAR                258
#define IDS_FT_MANDELBROT               259
#define IDS_FT_NEWTON                   260
#define IDS_HIST_DEL_ESC_TIMES_WARN     261
#define IDS_HIST_UNCACHE_IMAGE_WARN     262
#define IDS_HLINK_CANT_LAUNCH           263
#define IDS_IMG_BAD_SIZE                264
#define IDS_IMP_PAL_FILTER              265
#define IDS_JOB_ABORTED                 266
#define IDS_JOB_DEST                    267
#define IDS_JOB_DONE                    268
#define IDS_JOB_END                     269
#define IDS_JOB_FAILED                  270
#define IDS_JOB_FILTER                  271
#define IDS_JOB_LOAD_LIST               272
#define IDS_JOB_NAME                    273
#define IDS_JOB_POSTPONED               274
#define IDS_JOB_RUNNING                 275
#define IDS_JOB_SAVE_LIST               276
#define IDS_JOB_SOURCE                  277
#define IDS_JOB_START                   278
#define IDS_JOB_STATUS                  279
#define IDS_JOB_STOPPED_ERROR           280
#define IDS_JOB_WAITING                 281
#define IDS_MF_CANT_SHUTDOWN            282
#define IDS_MF_HELP_FILE_MISSING        283
#define IDS_MF_PREPARING_DEMO           284
#define IDS_MF_STOP_RECORD              285
#define IDS_MF_UNTITLED                 286
#define IDS_MF_VIEW_DEMO                287
#define IDS_MIDI_CANT_CREATE            288
#define IDS_MIDI_SETUP_FILTER           289
#define IDS_MIXER_FILTER                290
#define IDS_MIX_BAD_IMAGE_SIZE          291
#define IDS_MIX_IMAGE_SIZE_MISMATCH     292
#define IDS_MP_AUTOFADE_LOOP            293
#define IDS_MP_AUTOFADE_PLAY            294
#define IDS_MP_AUTOFADE_TIME            295
#define IDS_MP_COLOR_CYCLE_ENABLE       296
#define IDS_MP_COLOR_CYCLE_RATE         297
#define IDS_MP_COLOR_OFFSET             298
#define IDS_MP_CYCLE_LENGTH             299
#define IDS_MP_DAMPING                  300
#define IDS_MP_FADER_POS                301
#define IDS_MP_LISS_PHASE               302
#define IDS_MP_LISS_SPEED               303
#define IDS_MP_MIRROR                   304
#define IDS_MP_ORIGIN_MOTION            305
#define IDS_MP_ORIGIN_X                 306
#define IDS_MP_ORIGIN_Y                 307
#define IDS_MP_PAL_TWEEN_TIME           308
#define IDS_MP_PONG_SPEED               309
#define IDS_MP_SCROLL_DOWN              310
#define IDS_MP_SCROLL_LEFT              311
#define IDS_MP_SCROLL_RIGHT             312
#define IDS_MP_SCROLL_UP                313
#define IDS_MP_TEMPO                    314
#define IDS_MP_ZOOM_IN                  315
#define IDS_MP_ZOOM_OUT                 316
#define IDS_MS_CHAN                     317
#define IDS_MS_CTRL                     318
#define IDS_MS_EVENT                    319
#define IDS_MS_RANGE                    320
#define IDS_MS_RESET_WARN               321
#define IDS_MS_VALUE                    322
#define IDS_NET_ADAPTER_PROPS           323
#define IDS_OPTIONS                     324
#define IDS_OPTS_CUSTOM                 325
#define IDS_OPTS_DEFAULT_ITEM           326
#define IDS_OPTS_RESET_ALL              327
#define IDS_OPTS_RESTORE_DEFAULTS       328
#define IDS_OPTS_SNAP_NOT_FOUND         329
#define IDS_OPT_NO_MIDI_IN              330
#define IDS_PALETTE_FILTER              331
#define IDS_PAL_BKGND_COLOR             332
#define IDS_PARM_ANTIALIAS              333
#define IDS_PARM_COLOR_OFFSET           334
#define IDS_PARM_CYCLE_LEN              335
#define IDS_PARM_DEEP_ZOOM              336
#define IDS_PARM_EXPONENT               337
#define IDS_PARM_FRACTAL_TYPE           338
#define IDS_PARM_IMAGE_HEIGHT           339
#define IDS_PARM_IMAGE_WIDTH            340
#define IDS_PARM_MATH_PREC              341
#define IDS_PARM_NO                     342
#define IDS_PARM_PARAM                  343
#define IDS_PARM_QUALITY                344
#define IDS_PARM_VALUE                  345
#define IDS_PARM_YES                    346
#define IDS_PSTR_CANT_RESUME            347
#define IDS_PSTR_PAUSED_FILTER          348
#define IDS_PSTR_PAUSE_CHECK            349
#define IDS_PSTR_PAUSING                350
#define IDS_PSTR_RESUMING               351
#define IDS_PSTR_STOP_CHECK             352
#define IDS_PSTR_WRITING_BITMAP         353
#define IDS_RECORD                      354
#define IDS_REC_BAD_COLOR_CYCLE_RATE    355
#define IDS_REC_BAD_DURATION            356
#define IDS_REC_BAD_FRAME_RANGE         357
#define IDS_REC_BAD_FRAME_RATE          358
#define IDS_REC_BMP_CONTINUE            359
#define IDS_REC_BMP_DEST_FOLDER         360
#define IDS_REC_BMP_OVERWRITE           361
#define IDS_REC_CANT_CHANGE_PALETTE     362
#define IDS_REC_CANT_CREATE_FILTER      363
#define IDS_REC_CANT_LISTEN_SERVERS     364
#define IDS_REC_CHECKING_BITMAPS        365
#define IDS_REC_COMPLETE                366
#define IDS_REC_FINISHING               367
#define IDS_REC_NOT_ENOUGH_ZOOM         368
#define IDS_REC_PARAMS_DIFFER           369
#define IDS_REC_REPLACE_SCRIPT_WARN     370
#define IDS_REC_SAME_COORDS             371
#define IDS_REC_SELECT_POINTS           372
#define IDS_REC_TOO_FEW_POINTS          373
#define IDS_REC_ZOOM_OUT_OF_RANGE       374
#define IDS_REND_CANT_MULTI_RENDER      375
#define IDS_REND_STATUS                 376
#define IDS_SELECT_ITEMS                377
#define IDS_SLIDE_STATUS                378
#define IDS_SNAPSHOT_FILTER             379
#define IDS_SNAP_PROPERTIES             380
#define IDS_SNAP_PROPS_CAP              381
#define IDS_SRVFND_NO_SELECTION         382
#define IDS_SRVFND_UNAVAILABLE          383
#define IDS_SRV_ADDING_SERVERS          384
#define IDS_SRV_ALREADY_CONNECTED       385
#define IDS_SRV_BAD_SERVER              386
#define IDS_SRV_BAD_SNAP_FORMAT         387
#define IDS_SRV_BAD_VERSION             388
#define IDS_SRV_CANT_CONNECT            389
#define IDS_SRV_COL_CLIENT_HOST_NAME    390
#define IDS_SRV_COL_CLIENT_IP_ADDR      391
#define IDS_SRV_COL_DONE                392
#define IDS_SRV_COL_HOST_NAME           393
#define IDS_SRV_COL_IP_ADDR             394
#define IDS_SRV_COL_PROGRESS            395
#define IDS_SRV_COL_QUEUE               396
#define IDS_SRV_COL_RENDER_TIME         397
#define IDS_SRV_COL_THREAD_COUNT        398
#define IDS_SRV_LOCAL_HOST              399
#define IDS_SRV_NO_SERVERS_FOUND        400
#define IDS_SRV_PROPS                   401
#define IDS_SRV_PROPS_EX_CAPS           402
#define IDS_SRV_PROPS_TITLE             403
#define IDS_SRV_TIMEOUT                 404
#define IDS_SSE2_ODD_WIDTH              405
#define IDS_TEXT_FILTER                 406
#define IDS_TRAN_CANT_UNDO              407
#define IDS_TRAN_NO_PARAMS              408
#define IDS_UC_APPLY_PALETTE            409
#define IDS_UC_BOUNDS                   410
#define IDS_UC_COORDS                   411
#define IDS_UC_DRAG                     412
#define IDS_UC_EDIT_PALETTE             413
#define IDS_UC_HISTORY_CUT              414
#define IDS_UC_HISTORY_DELETE           415
#define IDS_UC_HISTORY_MOVE             416
#define IDS_UC_HISTORY_PASTE            417
#define IDS_UC_HISTORY_RENDER           418
#define IDS_UC_IMAGE_SIZE               419
#define IDS_UC_INVERT_COLOR             420
#define IDS_UC_OPEN_PALETTE             421
#define IDS_UC_ROTATE_HUE               422
#define IDS_UC_SCROLL                   423
#define IDS_UC_ZOOM                     424
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_TEXT                  1002
#define IDC_ABOUT_URL                   1003
#define IDC_ANTIALIAS_VALUE_EDIT        1004
#define IDC_ASRVL_BROWSE                1005
#define IDC_ASRVL_PATH_EDIT             1006
#define IDC_ASRV_HOSTNAME_EDIT          1007
#define IDC_BOUNDS_X1                   1008
#define IDC_BOUNDS_X2                   1009
#define IDC_BOUNDS_Y1                   1010
#define IDC_BOUNDS_Y2                   1011
#define IDC_CCYC_CYCLE_CHK              1012
#define IDC_CCYC_RATE_EDIT              1013
#define IDC_CCYC_RATE_SLIDER            1014
#define IDC_CLPK_COLOR                  1015
#define IDC_CLPK_EDIT_B                 1016
#define IDC_CLPK_EDIT_G                 1017
#define IDC_CLPK_EDIT_H                 1018
#define IDC_CLPK_EDIT_L                 1019
#define IDC_CLPK_EDIT_R                 1020
#define IDC_CLPK_EDIT_S                 1021
#define IDC_CLPK_SHADE                  1022
#define IDC_CLPK_SWATCH                 1023
#define IDC_CMAP_COLOR_OFS_EDIT         1024
#define IDC_CMAP_COLOR_OFS_SLIDER       1025
#define IDC_CMAP_CYCLE_LEN_EDIT         1026
#define IDC_CMAP_CYCLE_LEN_SLIDER       1027
#define IDC_COORDS_X                    1028
#define IDC_COORDS_Y                    1029
#define IDC_COORDS_Z                    1030
#define IDC_DRAG_MULTI                  1031
#define IDC_DRAG_SINGLE                 1032
#define IDC_EYEDROPPER                  1033
#define IDC_FB_LIST                     1034
#define IDC_FB_TAB                      1035
#define IDC_FSRV_METHOD                 1036
#define IDC_FSRV_METHOD2                1037
#define IDC_FSRV_RANGE_END              1038
#define IDC_FSRV_RANGE_START            1039
#define IDC_GRAD_COLOR_MODE_0           1040
#define IDC_GRAD_COLOR_MODE_1           1041
#define IDC_GRAD_DELETE                 1042
#define IDC_GRAD_GRADIENT               1043
#define IDC_GRAD_INSERT                 1044
#define IDC_GRAD_POS_EDIT               1045
#define IDC_GRAD_SPACE_EVENLY_CHK       1046
#define IDC_IMG_SIZE_HEIGHT_EDIT        1047
#define IDC_IMG_SIZE_WIDTH_EDIT         1048
#define IDC_IMSR_HEIGHT_EDIT            1049
#define IDC_IMSR_HEIGHT_UNIT            1050
#define IDC_IMSR_RESOLUTION_EDIT        1051
#define IDC_IMSR_RESOLUTION_UNIT        1052
#define IDC_IMSR_WIDTH_EDIT             1053
#define IDC_IMSR_WIDTH_UNIT             1054
#define IDC_JOB_ABORT                   1055
#define IDC_JOB_DELETE                  1056
#define IDC_JOB_LIST                    1057
#define IDC_JOB_MOVE_DOWN               1058
#define IDC_JOB_MOVE_UP                 1059
#define IDC_JOB_PERCENT                 1060
#define IDC_JOB_POSTPONE                1061
#define IDC_JOB_PROGRESS                1062
#define IDC_JOB_PROG_CAP                1063
#define IDC_JOB_SKIP                    1064
#define IDC_JOB_START                   1065
#define IDC_MIX_AUTOFADE_LOOP           1066
#define IDC_MIX_AUTOFADE_PLAY           1067
#define IDC_MIX_AUTOFADE_STOP           1068
#define IDC_MIX_AUTOFADE_TIME_EDIT      1069
#define IDC_MIX_AUTOFADE_TIME_SLIDER    1070
#define IDC_MIX_CHAN_SELECT             1071
#define IDC_MIX_CHAN_SELECT2            1072
#define IDC_MIX_FADER                   1073
#define IDC_MIX_MIRROR_CHK              1074
#define IDC_MIX_OPEN                    1075
#define IDC_MIX_ORG_MOTION_COMBO        1076
#define IDC_MIX_ORG_MOTION_PARAMS       1077
#define IDC_MIX_SAVE                    1078
#define IDC_MIX_SRC_A_COMBO             1079
#define IDC_MIX_SRC_B_COMBO             1080
#define IDC_MIX_TWEEN_TIME_EDIT         1081
#define IDC_MIX_TWEEN_TIME_SLIDER       1082
#define IDC_MSG_BOX_ICON                1083
#define IDC_MSG_BOX_TEXT                1084
#define IDC_MS_CHAN                     1085
#define IDC_MS_CHAN_SPIN                1086
#define IDC_MS_CTRL                     1087
#define IDC_MS_CTRL_SPIN                1088
#define IDC_MS_EVENT                    1089
#define IDC_MS_LEARN                    1090
#define IDC_MS_OPEN                     1091
#define IDC_MS_PAGE_SELECT              1092
#define IDC_MS_PAGE_SELECT2             1093
#define IDC_MS_PAGE_SELECT3             1094
#define IDC_MS_RANGE_END                1095
#define IDC_MS_RANGE_END_SPIN           1096
#define IDC_MS_RANGE_START              1097
#define IDC_MS_RANGE_START_SPIN         1098
#define IDC_MS_RESET                    1099
#define IDC_MS_SAVE                     1100
#define IDC_MS_TITLE                    1101
#define IDC_MS_VALUE                    1102
#define IDC_MULTI_FILE_PREVIEW          1103
#define IDC_OPTS_CACHE_IMAGES_CHK       1104
#define IDC_OPTS_CONT_ZOOM_STEP_EDIT    1105
#define IDC_OPTS_DEF_SNAP_BROWSE        1106
#define IDC_OPTS_DEF_SNAP_EDIT          1107
#define IDC_OPTS_DISPLAY_COMBO          1108
#define IDC_OPTS_DISPLAY_SIZE           1109
#define IDC_OPTS_FILE_FORMAT            1110
#define IDC_OPTS_FILE_FORMAT2           1111
#define IDC_OPTS_FRAME_RATE             1112
#define IDC_OPTS_GRID_COLOR             1113
#define IDC_OPTS_HUE_ROTATION           1114
#define IDC_OPTS_LISTEN_SERVERS_CHK     1115
#define IDC_OPTS_MIDI_DEVICE            1116
#define IDC_OPTS_MIDI_REFRESH           1117
#define IDC_OPTS_NET_ADAPTER_COMBO      1118
#define IDC_OPTS_NET_ADAPTER_PROPS      1119
#define IDC_OPTS_NET_DEF_PORT_CHK       1120
#define IDC_OPTS_NET_PORT_NUM_EDIT      1121
#define IDC_OPTS_PAL_EXPORT_SIZE        1122
#define IDC_OPTS_PAL_FIRST_BKGND        1123
#define IDC_OPTS_PAL_SMOOTH_WRAP        1124
#define IDC_OPTS_RECENT_PALETTES        1125
#define IDC_OPTS_RECENT_PARAMS          1126
#define IDC_OPTS_SAVE_CHGS_WARN_CHK     1127
#define IDC_OPTS_SAVE_ESC_TIMES_CHK     1128
#define IDC_OPTS_SCROLL_DELTA           1129
#define IDC_OPTS_THREADS_AUTO_CHK       1130
#define IDC_OPTS_THREAD_COUNT_EDIT      1131
#define IDC_OPTS_THUMB_HEIGHT_EDIT      1132
#define IDC_OPTS_THUMB_WIDTH_EDIT       1133
#define IDC_OPTS_UNDO_LEVELS_EDIT       1134
#define IDC_OPTS_UNDO_UNLIMITED_CHK     1135
#define IDC_OPTS_USE_SSE2_CHK           1136
#define IDC_OPTS_ZOOM_STEP_EDIT         1137
#define IDC_ORG_DAMPING_EDIT            1138
#define IDC_ORG_DAMPING_SLIDER          1139
#define IDC_ORG_LISS_PHASE_EDIT         1140
#define IDC_ORG_LISS_PHASE_SLIDER       1141
#define IDC_ORG_LISS_SPEED_EDIT         1142
#define IDC_ORG_LISS_SPEED_SLIDER       1143
#define IDC_ORG_LISS_XFREQ_EDIT         1144
#define IDC_ORG_LISS_XFREQ_SLIDER       1145
#define IDC_ORG_LISS_YFREQ_EDIT         1146
#define IDC_ORG_LISS_YFREQ_SLIDER       1147
#define IDC_ORG_PONG_SPEED_EDIT         1148
#define IDC_ORG_PONG_SPEED_SLIDER       1149
#define IDC_ORG_TEMPO_EDIT              1150
#define IDC_ORG_TEMPO_SLIDER            1151
#define IDC_PALN_NAME_EDIT              1152
#define IDC_PAL_BK_COLOR                1153
#define IDC_PAL_EDIT_NAME               1154
#define IDC_PAL_PREVIEW_CHK             1155
#define IDC_PARAMS_CTRL                 1156
#define IDC_POPR_ELAPSED                1157
#define IDC_POPR_FILENAME               1158
#define IDC_POPR_IMAGE_SIZE             1159
#define IDC_POPR_PAUSE                  1160
#define IDC_POPR_PCT_DONE               1161
#define IDC_POPR_PIXEL_RATE             1162
#define IDC_POPR_PROGRESS               1163
#define IDC_POPR_REMAINING              1164
#define IDC_POPR_ROWS_DONE              1165
#define IDC_PROGRESS                    1166
#define IDC_PROGRESS_MSG                1167
#define IDC_PROGRESS_PERCENT            1168
#define IDC_PSTR_ANTIALIAS_EDIT         1169
#define IDC_PSTR_QUEUE_JOB              1170
#define IDC_PSTR_RESUME                 1171
#define IDC_PSTR_SNAP_PIC               1172
#define IDC_QUALITY_VALUE_EDIT          1173
#define IDC_REC_CYCLE_COLORS_CHK        1174
#define IDC_REC_CYCLING_RATE_CAP        1175
#define IDC_REC_CYCLING_RATE_EDIT       1176
#define IDC_REC_DELETE                  1177
#define IDC_REC_DURATION_EDIT           1178
#define IDC_REC_DURATION_UNIT           1179
#define IDC_REC_DURATION_UNIT2          1180
#define IDC_REC_END_FRAME_CAP           1181
#define IDC_REC_END_FRAME_EDIT          1182
#define IDC_REC_FRAME_RANGE             1183
#define IDC_REC_FRAME_RANGE2            1184
#define IDC_REC_FRAME_RATE_EDIT         1185
#define IDC_REC_INSERT                  1186
#define IDC_REC_PARAMS_CTRL             1187
#define IDC_REC_QUEUE_JOB               1188
#define IDC_REC_SNAP_LIST               1189
#define IDC_REC_START_FRAME_CAP         1190
#define IDC_REC_START_FRAME_EDIT        1191
#define IDC_REC_TO_BITMAPS              1192
#define IDC_REC_X_CAP                   1193
#define IDC_REC_X_EDIT                  1194
#define IDC_REC_Y_CAP                   1195
#define IDC_REC_Y_EDIT                  1196
#define IDC_REC_Z_CAP                   1197
#define IDC_REC_Z_EDIT                  1198
#define IDC_REND_STATUS                 1199
#define IDC_RST_ABORT                   1200
#define IDC_RST_DURATION                1201
#define IDC_RST_ELAPSED                 1202
#define IDC_RST_FRAME_RATE              1203
#define IDC_RST_PCT_DONE                1204
#define IDC_RST_PROGRESS                1205
#define IDC_RST_RECORDED                1206
#define IDC_RST_REMAINING               1207
#define IDC_RST_RENDERING               1208
#define IDC_SELIMG_LIST                 1209
#define IDC_SLIDE_INTERVAL_EDIT         1210
#define IDC_SLIDE_INTERVAL_SLIDER       1211
#define IDC_SLIDE_LOOP                  1212
#define IDC_SLIDE_ORDER                 1213
#define IDC_SLIDE_ORDER2                1214
#define IDC_SLIDE_PAUSE                 1215
#define IDC_SLIDE_PLAY                  1216
#define IDC_SLIDE_STATUS                1217
#define IDC_SLIDE_STOP                  1218
#define IDC_SRVFND_LIST                 1219
#define IDC_SRVFND_SHOW_AVAIL_ONLY      1220
#define IDC_SRVSD_ACTION                1221
#define IDC_SRVSD_ACTION2               1222
#define IDC_SRVSD_ACTION3               1223
#define IDC_SRVSD_ACTION4               1224
#define IDC_SRV_ADD                     1225
#define IDC_SRV_ADD_LIST                1226
#define IDC_SRV_DELETE                  1227
#define IDC_SRV_FIND                    1228
#define IDC_SRV_LIST                    1229
#define IDC_SRV_SHOW_PROGRESS           1230
#define IDC_SRV_SHUTDOWN                1231
#define IDC_TOOL_HAND_CLOSED            1232
#define IDC_TOOL_HAND_OPEN              1233
#define IDC_TOOL_ZOOM                   1234
#define IDC_TOOL_ZOOM_IN                1235
#define IDC_TOOL_ZOOM_OUT               1236
#define IDC_TRAN_PALETTE_BROWSE         1237
#define IDC_TRAN_PALETTE_EDIT           1238
#define IDC_TRAN_PARAMS_CTRL            1239
#define IDC_TRAN_RENDER_CHK             1240
#define IDC_WARNING_ICON                1241
#define ID_APP_CANCEL                   32771
#define ID_APP_HOME_PAGE                32772
#define ID_EDIT_BOUNDS                  32773
#define ID_EDIT_COORDS                  32774
#define ID_EDIT_DELETE                  32775
#define ID_EDIT_OPTIONS                 32776
#define ID_EDIT_TOOL_HAND               32777
#define ID_EDIT_TOOL_MARQUEE            32778
#define ID_EDIT_TOOL_ZOOM               32779
#define ID_FB_FILE_OPEN                 32780
#define ID_FB_FILE_PROPS                32781
#define ID_FB_PARENT_FOLDER             32782
#define ID_FB_RENAME                    32783
#define ID_FB_SORT_DATE                 32784
#define ID_FB_SORT_NAME                 32785
#define ID_FB_SORT_SIZE                 32786
#define ID_FB_SORT_TYPE                 32787
#define ID_FB_VIEW_ICON                 32788
#define ID_FB_VIEW_LIST                 32789
#define ID_FB_VIEW_REPORT               32790
#define ID_FB_VIEW_SMALL_ICON           32791
#define ID_FILE_EXPORT                  32792
#define ID_FILE_POSTER                  32793
#define ID_FILE_RECORD                  32794
#define ID_FILE_RECORD_STOP             32795
#define ID_GRAD_DELETE                  32796
#define ID_GRAD_INSERT_AT               32797
#define ID_GRAD_INVERT_COLOR            32798
#define ID_GRAD_REVERSE_CYCLE           32799
#define ID_GRAD_ROTATE_HUE              32800
#define ID_GRAD_SELECT_ALL              32801
#define ID_HISTORY_VIEW                 32802
#define ID_HIST_RECORD                  32803
#define ID_IMG_ANTIALIAS_0              32804
#define ID_IMG_ANTIALIAS_1              32805
#define ID_IMG_ANTIALIAS_2              32806
#define ID_IMG_ANTIALIAS_3              32807
#define ID_IMG_ANTIALIAS_4              32808
#define ID_IMG_CANCEL                   32809
#define ID_IMG_CTX_ZOOM_IN              32810
#define ID_IMG_CTX_ZOOM_OUT             32811
#define ID_IMG_CYCLE_COLORS             32812
#define ID_IMG_DELETE_ESC_TIMES         32813
#define ID_IMG_FIT_IN_WINDOW            32814
#define ID_IMG_FRACTAL_TYPE_1           32815
#define ID_IMG_FRACTAL_TYPE_2           32816
#define ID_IMG_FRACTAL_TYPE_3           32817
#define ID_IMG_HISTORY_EXPORT           32818
#define ID_IMG_IMAGE_SIZE_0             32819
#define ID_IMG_IMAGE_SIZE_1             32820
#define ID_IMG_IMAGE_SIZE_2             32821
#define ID_IMG_IMAGE_SIZE_3             32822
#define ID_IMG_IMAGE_SIZE_4             32823
#define ID_IMG_MRU_ANTIALIAS1           32824
#define ID_IMG_MRU_ANTIALIAS2           32825
#define ID_IMG_MRU_ANTIALIAS3           32826
#define ID_IMG_MRU_ANTIALIAS4           32827
#define ID_IMG_MRU_ANTIALIAS5           32828
#define ID_IMG_MRU_ANTIALIAS6           32829
#define ID_IMG_MRU_ANTIALIAS7           32830
#define ID_IMG_MRU_ANTIALIAS8           32831
#define ID_IMG_MRU_ANTIALIAS9           32832
#define ID_IMG_MRU_IMAGE_SIZE1          32833
#define ID_IMG_MRU_IMAGE_SIZE2          32834
#define ID_IMG_MRU_IMAGE_SIZE3          32835
#define ID_IMG_MRU_IMAGE_SIZE4          32836
#define ID_IMG_MRU_IMAGE_SIZE5          32837
#define ID_IMG_MRU_IMAGE_SIZE6          32838
#define ID_IMG_MRU_IMAGE_SIZE7          32839
#define ID_IMG_MRU_IMAGE_SIZE8          32840
#define ID_IMG_MRU_IMAGE_SIZE9          32841
#define ID_IMG_MRU_PALETTE1             32842
#define ID_IMG_MRU_PALETTE2             32843
#define ID_IMG_MRU_PALETTE3             32844
#define ID_IMG_MRU_PALETTE4             32845
#define ID_IMG_MRU_PALETTE5             32846
#define ID_IMG_MRU_PALETTE6             32847
#define ID_IMG_MRU_PALETTE7             32848
#define ID_IMG_MRU_PALETTE8             32849
#define ID_IMG_MRU_PALETTE9             32850
#define ID_IMG_MRU_QUALITY1             32851
#define ID_IMG_MRU_QUALITY2             32852
#define ID_IMG_MRU_QUALITY3             32853
#define ID_IMG_MRU_QUALITY4             32854
#define ID_IMG_MRU_QUALITY5             32855
#define ID_IMG_MRU_QUALITY6             32856
#define ID_IMG_MRU_QUALITY7             32857
#define ID_IMG_MRU_QUALITY8             32858
#define ID_IMG_MRU_QUALITY9             32859
#define ID_IMG_PALETTE_EXPORT           32860
#define ID_IMG_PALETTE_IMPORT           32861
#define ID_IMG_PALETTE_OPEN             32862
#define ID_IMG_PALETTE_SAVE             32863
#define ID_IMG_PAL_INVERT_COLOR         32864
#define ID_IMG_PAL_ROTATE_HUE           32865
#define ID_IMG_QUALITY_0                32866
#define ID_IMG_QUALITY_1                32867
#define ID_IMG_QUALITY_2                32868
#define ID_IMG_QUALITY_3                32869
#define ID_IMG_RENDER                   32870
#define ID_IMG_SLIDE_SHOW               32871
#define ID_IMG_TRANSFORM                32872
#define ID_IMG_UNCACHE_IMAGE            32873
#define ID_IMG_ZOOM_IN                  32874
#define ID_IMG_ZOOM_OUT                 32875
#define ID_INDICATOR_ANTIALIAS          32876
#define ID_INDICATOR_FRAME_SIZE         32877
#define ID_INDICATOR_QUALITY            32878
#define ID_JOB_EDIT_CLEAR_LIST          32879
#define ID_JOB_EDIT_DELETE              32880
#define ID_JOB_EDIT_DELETE_DONE         32881
#define ID_JOB_EDIT_DONE_WAITING        32882
#define ID_JOB_EDIT_FAILED_WAITING      32883
#define ID_JOB_EDIT_POSTPONE            32884
#define ID_JOB_EDIT_POSTPONED_WAITING   32885
#define ID_JOB_EDIT_SKIP                32886
#define ID_JOB_EDIT_WAITING_POSTPONED   32887
#define ID_JOB_FILE_LOAD_LIST           32888
#define ID_JOB_FILE_SAVE_LIST           32889
#define ID_JOB_OPTS_SHUTDOWN            32890
#define ID_JOB_VIEW_ERROR               32891
#define ID_LEVELS_VIEW                  32892
#define ID_LEVS_SCALING_TYPE            32893
#define ID_LEVS_SCALING_TYPE2           32894
#define ID_LEVS_SHOW_AXIS               32895
#define ID_PARAMS_VIEW                  32896
#define ID_RH_RESET_COLS                32897
#define ID_SNAP_DELETE                  32898
#define ID_SNAP_INSERT                  32899
#define ID_SNAP_PROPERTIES              32900
#define ID_SNAP_SELECT_ALL              32901
#define ID_SRV_DELETE                   32902
#define ID_SRV_PROPERTIES               32903
#define ID_SRV_SHUTDOWN                 32904
#define ID_VIEW_COLOR_CYCLING           32905
#define ID_VIEW_COLOR_MAPPING           32906
#define ID_VIEW_DEMO                    32907
#define ID_VIEW_FILES                   32908
#define ID_VIEW_GRID                    32909
#define ID_VIEW_HISTORY                 32910
#define ID_VIEW_JOB_CONTROL             32911
#define ID_VIEW_LEVELS                  32912
#define ID_VIEW_MIDI_SETUP              32913
#define ID_VIEW_MIXER                   32914
#define ID_VIEW_PALETTE                 32915
#define ID_VIEW_PARAMS                  32916
#define ID_VIEW_RECORD                  32917
#define ID_VIEW_RECORD_STATUS           32918
#define ID_VIEW_SERVERS                 32919
#define ID_WND_EXCLUSIVE                32920
#define ID_WND_FULL_SCREEN              32921

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        425
#define _APS_NEXT_COMMAND_VALUE         32922
#define _APS_NEXT_CONTROL_VALUE         1242
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
